spring.application.name=weather_test

spring.datasource.url=jdbc:postgresql://localhost:5432/Weather_History
spring.datasource.username=postgres
spring.datasource.password=eve@123
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB
spring.servlet.multipart.enabled=true


